Cafuego/ops 10284 issue lister
UN-OCHA/actions pull request #38
Opened 2024-10-30 02:05 UTC by cafuego

2024-10-31 23:42 UTC, orakili requested changes
Thanks, that's useful. I think the regex doesn't capture enough though, see suggestion.

2024-11-01 00:43 UTC, cafuego commented on drupal-issues/entrypoint.js
> +const regex = `@see (?<link>(?:(?:[a-z]+:)?//)(?:www\\.drupal\\.org)/project/[^\\s"]*/issues/(?<issue>[^\\s".?!]*)?)`;
I was considering that, but if we pull out all drupal.org links we may also end up with a bunch of non-issue nodes. I suppose I should see what that does to the api call, eh.

2024-11-01 01:30 UTC, orakili commented on drupal-issues/entrypoint.js
> +const regex = `@see (?<link>(?:(?:[a-z]+:)?//)(?:www\\.drupal\\.org)/project/[^\\s"]*/issues/(?<issue>[^\\s".?!]*)?)`;
Is the scan limited to the site/module repo? There are less than 20 drupal.org URLs found with that regex, per repo for RW, RWR, UNO, WHD, CD etc.

A few links may not be drupal issues but I think they can be filtered out by checking if `field_issue_status` is present and/or is a value in the list of issues.

2024-11-04 00:15 UTC, orakili approved these changes

2024-11-06 00:47 UTC, merged